const mongoose = require('mongoose');

const guildSchema = new mongoose.Schema({
  guildId: { type: String, required: true, unique: true },
  guildName: String,
  ownerId: String,
  channels: {
    welcome: String,
    rules: String,
    announcements: String,
    ticketLog: String,
    verificationLog: String,
    securityLog: String,
    modLog: String,
    staffChat: String,
    generalChat: String,
    voiceGeneral: String,
    voiceTemp: String,
    ticketCategory: String,
    departmentCategories: {
      politie: String,
      pompieri: String,
      medic: String,
      dot: String,
    },
  },
  roles: {
    founder: String,
    admin: String,
    mod: String,
    helper: String,
    helper: String,
    verified: String,
    unverified: String,
    citizen: String,
    departments: {
      politie: { role: String, ranks: Map },
      pompieri: { role: String, ranks: Map },
      medic: { role: String, ranks: Map },
      dot: { role: String, ranks: Map },
    },
    colors: Map,
    levelRoles: Map,
  },
  settings: {
    prefix: { type: String, default: '!' },
    autoRole: String,
    welcomeChannel: String,
    levelChannel: String,
    ticketEnabled: { type: Boolean, default: true },
    verificationEnabled: { type: Boolean, default: false },
    securityEnabled: { type: Boolean, default: true },
    antiRaid: { type: Boolean, default: true },
    antiSpam: { type: Boolean, default: true },
    antiNuke: { type: Boolean, default: true },
    autoBanNewAccounts: { type: Boolean, default: true },
  },
  security: {
    maxJoinsPerMinute: { type: Number, default: 5 },
    maxMessagesPerSecond: { type: Number, default: 3 },
    maxMentionsPerMessage: { type: Number, default: 5 },
    maxLinksPerMessage: { type: Number, default: 3 },
    autoBanNewAccountDays: { type: Number, default: 7 },
    botWhitelist: [String],
  },
  panels: {
    ticket: String,
    verify: String,
    rules: String,
    roles: String,
    departments: String,
    security: String,
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Guild', guildSchema);
